[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.11.0",
    "isort>=7.0.0",
    "langchain",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.0",
    "langchain-openai>=1.1.0",
    "langchain-tavily>=0.2.14",
    "langchainhub>=0.1.21",
    "langgraph>=1.0.4",
    "langsmith>=0.4.53",
    "python-dotenv>=1.2.1",
    "tavily-python>=0.7.15",
]
